### ISSUE TITLE
How can we add / bind the property dynamically?

### ISSUE THREAD

**Issue by muraray** [b9chris/GracefulDynamicDictionary#1]
For non nullable dynamic objects we can use to add the properties dynamically
as follows 

```
User users = GetUser(); \\ Just a fake data here
dynamic Roles = new ExpandoObject() as IDictionary<string, object> \newline
if (null != user)
     if (user.RoleList != null && user.RoleList.Any())
          user.RoleList.ForEach(role => {
               if (role != null)
                     ((IDictionary<string, object>)roles).Add(role.RoleCode, role.RoleCode);
                });
```

How can we add / bind the property dynamically? using GracefulDynamicDictionary...

**Comment by b9chris** [comment]
I think that code formatting might've fallen apart, I applied an edit as a proposal to see if it's what you meant? Let me know if it's right.

I think what you're asking is how can I use this class for Roles here, yes?
If my understanding is right it would look like this

    var roles = new GracefulDynamicDictionary();
    ...
    roles.Add(role.RoleCode, role);

Note that I may have fixed a bug for you here in the process - the code you had added the string twice, once as key once as value, rather than the role object itself. Here I'm adding the actual role. If this code happened to access a role named "Ops", you could later get it like:

    var role = roles.Ops; // assigns the Ops role to variable, or null if not added.
